---
title: "UFO Sightings and COVID-19"
author: "Group 7 - Evan Conaway, James Seidel, Sarah Derda"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
```


```{r libraries_setup, include = FALSE, eval=TRUE}

library(flexdashboard)
library(readr)
library(lubridate)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(raster)
library(tidyverse)
library(usmap)
library(ggmap)
library(maps)
library(readxl)
library(ggrepel)
library(gridExtra)
library(dplyr)

```

```{r data_import, include = FALSE, eval=TRUE}

cases_pop_county <- read.csv("raw-data/counties_pop_casew.csv")
ufo <- read.csv("raw-data/ufo_withlatlong.csv")
USA <- getData("GADM", country = "usa", level = 2)

popup_dat <- paste0("<strong>County: </strong>", 
                    cases_pop_county$county, 
                    "<br><strong>Cases Per 100,000: </strong>", 
                    floor(cases_pop_county$casepercap))

popup_ufo <- paste0("<strong>Description: </strong>", 
                      ufo$Description)

```

### Interactive Map Showing UFO Sightings and Confirmed Cases of COVID-19 per 100,000 {data-commentary-width=350}

```{r interactive_map, eval=TRUE}

pal <- colorQuantile("YlOrRd", NULL, n = 9)
leaflet() %>% 
  addTiles() %>% 
  fitBounds(-102.03,37,-109.03, 41) %>% 
  addTiles() %>% 
  addPolygons(data = USA,
              fillColor = ~pal(cases_pop_county$casepercap), 
              fillOpacity = 0.6, 
              color = "#BDBDC3", 
              weight = 1,
              popup = popup_dat) %>% 
  addMarkers(ufo$lon, 
             ufo$lat, 
             clusterOptions = markerClusterOptions(),
             icon = makeIcon("alien.png"),
             popup = popup_ufo) %>% 
  addLegend(position = "bottomleft", pal = pal, values = cases_pop_county$casepercap,
            title = "Cases per 100,000",
            opacity = 1)

```

*** 

Some commentary about Frame 1.

```{r scatterplot_framework, include = FALSE, eval=TRUE}

# Read in data
covid <- read_csv("raw-data/covidcases.csv")
ufobycounty <- read_csv("JamesWork/ufo2019counties") 

ufobycounty<- drop_na(ufobycounty)

#prepared data

ufobystate <- ufobycounty %>% 
  group_by(State) %>% 
  count() %>% 
  ungroup()

ufobystate <- mutate(.data = ufobystate, state_name = c("Alabama", "Arizona", 
                                          "Arkansas", "California", "Colorado", 
                                          "Connecticut", "Delaware", 
                                          "Florida", "Georgia","Idaho", 
                                          "Illinois", "Indiana", "Iowa", "Kansas", 
                                          "Kentucky", "Louisiana", "Maine", 
                                          "Maryland", "Massachusetts", "Michigan", 
                                          "Minnesota",
                                          "Mississippi", "Missouri", "Montana", 
                                          "Nebraska", "Nevada", "New Hampshire", 
                                          "New Jersey", "New Mexico", "New York", 
                                          "North Carolina", "North Dakota",
                                          "Ohio", "Oklahoma", "Oregon", "Pennsylvania",
                                          "Rhode Island", "South Carolina", "South Dakota", 
                                          "Tennessee", "Texas","Utah", "Vermont", 
                                          "Virginia", "Washington", "West Virginia", 
                                          "Wisconsin", "Wyoming"))

covidbystate <- covid %>% 
  group_by(state) %>% 
  count() %>% 
  ungroup() 

covidbystate <- covidbystate[-c(2, 9, 12, 13, 37, 42, 50),]

statepopulations <- read_excel("JamesWork/Statepopulations.xlsx")

ufoandcovid <- ufobystate %>%
  mutate(covid_cases = covidbystate$n) %>% 
  mutate(ufo_sightings = ufobystate$n) %>% 
  mutate(population = statepopulations$Population) %>% 
  mutate(covid_per_cap = covid_cases/population) %>% 
  mutate(ufo_per_cap = ufo_sightings/population)

##ggplots with data

ufoandcovid

statenames <- ufoandcovid$State
statenames[with(ufoandcovid, 
                !(covid_cases > 27000 | ufo_sightings > 185))] <- ""

plotone <- ufoandcovid %>% 
ggplot(aes(x=ufo_sightings, y = covid_cases)) +
  geom_point() +
  geom_text(label = statenames, size = 3, nudge_x = 18)+
  labs(title = "2020 COVID cases by 2019 UFO sightings in the lower 48 states (per capita on right)")+
  xlab("UFO sightings") +
  ylab("COVID cases") +
  theme_tufte()

statenames2 <- ufoandcovid$State
statenames2[with(ufoandcovid, !(covid_per_cap > 0.01 | ufo_per_cap > 0.00005))] <- ""


plottwo <- ufoandcovid %>% 
  ggplot(aes(x=ufo_per_cap, y = covid_per_cap,)) +
  geom_point() +
  geom_text(label = statenames2, size = 3,
             position = position_nudge(x = 0.00001))+
  labs(x = "UFO sightings per capita", y = "Covid Cases per capita")+
  theme_tufte() +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank(),
        axis.text.y = element_blank())

#newcode

ply1 <- ggplotly(plotone)
ply2 <- ggplotly(plottwo)


```

### Looking into 2020 COVID-19 Cases and 2019 UFO Sightings in the Lower 48 States  {data-commentary-width=350}

```{r scatterplots_final, eval=TRUE}



subplot(ply1, ply2, nrows=1)

```

*** 

Some commentary about Frame 2.

### Table of Total Deaths per County in the United States {data-commentary-width=350}

```{r death_table, eval= TRUE}

### This script is designed to create the data table for our flex dashboard.
### It is a table of all the Covid Deaths. It is included to remind us of everyone that has passed due 
### to this pandemic. 

covid <- read_csv("raw-data/covidcases.csv")

covid <- covid %>% 
  mutate(County = paste(covid$county,covid$state,sep = ", "))

covid <- covid %>% 
    group_by(County) %>% 
  dplyr::summarise(Deaths = last(deaths))

### This code chunk works better when knit into flexdashboard

datatable(covid, 
          colnames = c("County", "Deaths"), 
          extensions = "Scroller", style="bootstrap", 
          class="compact", width="100%", 
          options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))

```

***

Some commentary about Frame 3.
